//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartList
    {
        public int o_Id { get; set; }
        public int o_fk_pro { get; set; }
        public int o_fk_inv { get; set; }
        public System.DateTime o_date { get; set; }
        public int o_qty { get; set; }
        public int o_bill { get; set; }
        public int o_unitprice { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProdMst ProdMst { get; set; }
    }
}
