//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimMst
    {
        public string Style_Code { get; set; }
        public int DimQlty_Id { get; set; }
        public int DimSubType_Id { get; set; }
        public string Dim_Crt { get; set; }
        public string Dim_Pcs { get; set; }
        public string Dim_Gm { get; set; }
        public string Dim_Size { get; set; }
        public string Dim_Rate { get; set; }
        public string Dim_Amt { get; set; }
    
        public virtual DimQltyMst DimQltyMst { get; set; }
        public virtual DimQltySubMst DimQltySubMst { get; set; }
        public virtual ItemMst ItemMst { get; set; }
    }
}
