//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMst()
        {
            this.DimMsts = new HashSet<DimMst>();
            this.StoneMsts = new HashSet<StoneMst>();
        }
    
        public string Style_Code { get; set; }
        public string Pairs { get; set; }
        public int Brand_Id { get; set; }
        public string Quantity { get; set; }
        public int Cat_Id { get; set; }
        public string Prod_Quality { get; set; }
        public int Certify_Id { get; set; }
        public int Prod_Id { get; set; }
        public int GoldType_Id { get; set; }
        public string Gold_Wt { get; set; }
        public string Stone_Wt { get; set; }
        public string Net_Gold { get; set; }
        public string Wstg_Per { get; set; }
        public string Wstg { get; set; }
        public string Tot_Gross_Wt { get; set; }
        public string Gold_Rate { get; set; }
        public string Gold_Amt { get; set; }
        public string Gold_Making { get; set; }
        public string Stone_Making { get; set; }
        public string Other_Making { get; set; }
        public string Tot_Making { get; set; }
        public string MRP { get; set; }
    
        public virtual BrandMst BrandMst { get; set; }
        public virtual CatMst CatMst { get; set; }
        public virtual CertifyMst CertifyMst { get; set; }
        public virtual GoldKrtMst GoldKrtMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DimMst> DimMsts { get; set; }
        public virtual ProdMst ProdMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoneMst> StoneMsts { get; set; }
    }
}
