//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineJewelleryShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoneMst
    {
        public string Style_Code { get; set; }
        public int StoneQlty_Id { get; set; }
        public string Stone_Gm { get; set; }
        public string Stone_Pcs { get; set; }
        public string Stone_Ot { get; set; }
        public string Stone_Rate { get; set; }
        public string Stone_Amt { get; set; }
    
        public virtual ItemMst ItemMst { get; set; }
        public virtual StoneQltyMst StoneQltyMst { get; set; }
    }
}
